# Exceções
# try:
#     print(a)
# except:
#     print('Ocorreu um erro!')

# try:
#     n1, n2 = int(input('Digite um número: ')), int(input('Digite um número: '))
#     print(n1 + n2)
# except ValueError as erro:
#     print('Por favor, digite um número!', erro)



# Try, except, else, finally
# Try e else: será executado se não haver erros
# except: Será executado se houver erros
# finally: Sempre será executado
# try:
#     n1 = int(input("Digite um número: "))
# except:
#     print('Erro!')
# else:
#     print('Código executado com sucesso!')
# finally:
#     print('Código executado')